In [ ]:
Q1. What are the benefits of the built-in array package, if any?


In python array is abuilt in function and it is like a list in python and there is no major differences in the list and array
By using the built in packages we can get the code simpler and also having like the seperate package in python called
numpy it is like numerical python.

In [ ]:
Q2. What are some of the array package's limitations?


the dimension of an array is determined the moment the array is created, and cannot be changed later 
the array occupies an amount of memory that is proportional to its size, independently of the number of elements that are 
actually of interest

In [ ]:
Q3. Describe the main differences between the array and numpy packages.



Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools 
for working with these arrays. A numpy array is a grid of values, all of the same type, and is indexed by a tuple of 
nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers 
giving the size of the array along each dimension.
The Python core library provided Lists. A list is the Python equivalent of an array, but is resizeable and can contain
elements of different types.

In [ ]:
Explain the distinctions between the empty, ones, and zeros functions.


empty() Return a new array of given shape and type, without initializing entries..
ones() Return a new array of given shape and type, filled with ones.
zeros() Return a new array of given shape and type, filled with zeros.

In [14]:
import numpy as np
print(np.zeros(10))
print(np.ones(2,np.int8))
print(np.empty(1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1]
[0.]


In [ ]:
Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?



The fromfunction() function is used to construct an array by executing a function over each coordinate.

In [15]:
import numpy as np
a = np.fromfunction(lambda i, j: i * j, (4, 4), dtype = float)    
print(a)

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [ ]:
Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?




In [17]:
a = np.array([1, 2, 3, 4])
print(a + 1)
print(2**a)



[2 3 4 5]
[ 2  4  8 16]


In [ ]:
Q7. Can array-to-scalar operations use combined operation-assign operators (such as + or *)? What is the outcome?

In [20]:
a = np.array([1, 2, 3, 4])
print(a + 1)
print(a*1)


[2 3 4 5]
[1 2 3 4]


In [ ]:
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?




In [22]:
country = np.array(['USA', 'Japan', 'UK',  'India', 'China'])
print(country)

['USA' 'Japan' 'UK' 'India' 'China']


In [ ]:
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?




In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(a+b)
print(a*b)

[5 5 5 5]
[4 6 6 4]


In [ ]:
Q10. What is the best way to use a Boolean array to mask another array?


masking means manipulated data in a collection based on some criteria. The criteria you use is typically of a true or false
nature, hence the boolean part. Boolean masking is typically the most efficient way to quantify a sub-collection in a 
collection.

In [ ]:
Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.


We can get the standard deviation using the numpy packages and by using the stats package and and our own python and by all 
that we can fastly gets by using the numpy package.